spring.application.name=Ex08DevTools
# 1. \uCF58\uC194\uC5D0 ANSI \uC0C9\uC0C1 \uCD9C\uB825\uC744 \uD56D\uC0C1 \uD65C\uC131\uD654 (\uAC00\uC7A5 \uAE30\uBCF8!)
spring.output.ansi.enabled=always
spring.thymeleaf.cache=false

# 2. \uB85C\uADF8\uB97C \uB354 \uC608\uC058\uACE0 \uAC00\uB3C5\uC131 \uC788\uAC8C \uB9CC\uB4DC\uB294 \uCEE4\uC2A4\uD140 \uD328\uD134 (\uC120\uD0DD \uC0AC\uD56D)
# \uB0A0\uC9DC(\uD68C\uC0C9), \uB85C\uADF8\uB808\uBCA8(\uC0C9\uC0C1\uBCC4), PID(\uC790\uC8FC\uC0C9), \uD074\uB798\uC2A4\uBA85(\uCCAD\uB85D\uC0C9) \uB4F1\uC73C\uB85C \uAD6C\uBD84\uB429\uB2C8\uB2E4.
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}

# \uC790\uBC14 \uC18C\uC2A4 \uCF54\uB4DC \uBCC0\uACBD\uC2DC \uC11C\uBC84\uB97C \uB2E4\uC2DC \uC2DC\uC791\uD560\uC9C0
spring.devtools.restart.enabled = true

#\uC815\uC801 \uB9AC\uC18C\uC2A4(html,css,js)\uBCC0\uACBD\uC2DC \uBE0C\uB77C\uC6B0\uC800 \uC790\uB3D9 \uC0C8\uB85C\uACE0\uCE68 \uD560\uC9C0
spring.devtools.livereload.enabled = true

spring.devtools.restart.exclude=static/**,templates