spring.application.name=Ex09Model
# 1. ??? ANSI ?? ??? ?? ??? (?? ??!)
spring.output.ansi.enabled=always
spring.thymeleaf.cache=false
spring.devtools.restart.exclude=static/**templates/**

# 2. ??? ? ??? ??? ?? ??? ??? ?? (?? ??)
# ??(??), ????(???), PID(???), ????(???) ??? ?????.
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}