spring.application.name=Ex14LoginJoinDB

# \uC624\uB77C\uD074 CE\uBC84\uC804 - 8080\uD3EC\uD2B8\uAC00 \uAE30\uBCF8\uC774\uB77C\uC11C \uD3EC\uD2B8 \uCDA9\uB3CC\uC774 \uB0A8. \uD3EC\uD2B8 \uD68C\uD53C.

# thymeleaf
spring.thymeleaf.cache=false


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true

# ?? ? ?? ??? ???
spring.devtools.restart.enabled=true
# ?? ???(HTML ?) ?? ? ?? ??
spring.devtools.livereload.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/loginjoin?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=gkeptm20010030

# logging
logging.level.org.hibernate.type.description.sql.BasicBinder=trace
logging.level.org.hibernate.SQL=debug
# Hibernate 6.1.5 updated in springboot 3.x, 4.x
logging.level.org.hibernate.orm.jdbc.bind=trace



spring.output.ansi.enabled=always

# 2. \uB85C\uADF8\uB97C \uB354 \uC608\uC058\uACE0 \uAC00\uB3C5\uC131 \uC788\uAC8C \uB9CC\uB4DC\uB294 \uCEE4\uC2A4\uD140 \uD328\uD134 (\uC120\uD0DD \uC0AC\uD56D)
# \uB0A0\uC9DC(\uD68C\uC0C9), \uB85C\uADF8\uB808\uBCA8(\uC0C9\uC0C1\uBCC4), PID(\uC790\uC8FC\uC0C9), \uD074\uB798\uC2A4\uBA85(\uCCAD\uB85D\uC0C9) \uB4F1\uC73C\uB85C \uAD6C\uBD84\uB429\uB2C8\uB2E4.
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}