# thymeleaf
spring.thymeleaf.cache=false

# JPA ??
# none: ???. ?????? ???? ??? ??? ?? ????.
# update: ??? ???? ?? ??? ???? ?????? ???? ???????. (?? ??? ??)
# create: ?????? ?? ? ?? ???? ???? ?? ?????. (?? ??? ???)
# create-drop: ?????? ?? ? ???? ????, ?? ? ???? ???? ?? ?????.
# validate: ??? ??? ?????? ??? ??? ?????? ?????. ?? ?? ??? ????? ???? ????.
spring.jpa.hibernate.ddl-auto=none

# DDL ?? ?? ??? ???? ?? (????? ddl-auto ??? ???)
spring.jpa.generate-ddl=false

# ???? SQL ??? ?? ??? ??
spring.jpa.show-sql=true

# ??? ??????? ??(Dialect) ?? - MySQL 8 ??? ???? SQL ??
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# pretty sql format
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=gkeptm20010030

# logging
logging.level.org.hibernate.type.description.sql.BasicBinder=trace
logging.level.org.hibernate.SQL=debug
# Hibernate 6.1.5 updated in springboot 3.x
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.output.ansi.enabled=always